language: go

go:
  - "1.x"

script:
- $HOME/gopath/src/github.com/Undermove/RockScissorPaperWebInterface/scripts/build.sh

notifications:
  email: false

deploy:
  skip_cleanup: true
  provider: script
  script: scripts/deploy.sh
  on:
    branch: master